- name: Create a Test File on Windows
  hosts: stg
  gather_facts: no

  tasks:
    - name: Create a test file
      win_file:
        path: C:\testfile.txt
        state: touch
        content: "This is a test file created by Ansible"
