---
- name: Install Python on Windows Server
  hosts: windows
  tasks:
    - name: Download Python installer
      win_get_url:
        url: https://www.python.org/ftp/python/3.12.0/python-3.12.0-amd64.exe
        dest: C:\Temp\python-installer.exe
        validate_certs: no

    - name: Install Python
      win_package:
        path: C:\Temp\python-installer.exe
        arguments: /quiet InstallAllUsers=1 PrependPath=1
        state: present

    - name: Verify Python installation
      win_shell: python --version
      register: python_version

    - name: Display Python version
      debug:
        msg: "Python installed successfully. Version: {{ python_version.stdout }}"
