name: Ansible Playbook Execution

on:
  workflow_dispatch:

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible and Dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible python3-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install pywinrm pywinrm[credssp] requests

      - name: Verify Ansible Installation
        run: |
          ansible --version

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ./Ansible/hosts.ini ./Ansible/playbook.yaml -vvv
